In [1]:
import numpy as np 

In [2]:
A = np.array ([[1,2,3,2] , [4,5,6,1] , [7,8,9,10]])

In [3]:
A

array([[ 1,  2,  3,  2],
       [ 4,  5,  6,  1],
       [ 7,  8,  9, 10]])

In [4]:
A [0:2 , 2:4]

array([[3, 2],
       [6, 1]])

In [6]:
A [1: , :3]

array([[4, 5, 6],
       [7, 8, 9]])

In [9]:
B = A [2, 1:3 ]
B [0] = 1000
A

array([[   1,    2,    3,    2],
       [   4,    5,    6,    1],
       [   7, 1000,    9,   10]])

In [12]:
B = np.array ([[[1,2,3] ,
              [4,5,6] ],
              [[7,8,9] ,
              [10,11,12]]]) 
B.ndim
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
B [0 , 0 , 0]

np.int64(1)

In [23]:
B [:, :,0]

array([[ 1,  4],
       [ 7, 10]])

In [24]:
B [0 , : , 1]

array([2, 5])

In [25]:
B [1 , : , 1:]

array([[ 8,  9],
       [11, 12]])

In [27]:
B [: , 0 , 1:]

array([[2, 3],
       [8, 9]])