In [1]:
import numpy as np 

A = np.array ([[1,2,3,4],
             [5,6,7,8]])
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
np.ones ([3,3])
np.zeros ([3,3]) 
np.eye (4)
np.full ([3,3] , 10 ) 
np.arange (1,10) 
np.linspace (1,5,5) 

array([1., 2., 3., 4., 5.])

In [15]:
A.shape 
A.ndim
A.size 
A.dtype 

dtype('int64')

In [16]:
A.astype ("str") 

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8']], dtype='<U21')

In [19]:
A.reshape (4,2)
A.flatten ()

array([1, 2, 3, 4, 5, 6, 7, 8])