In [1]:
import numpy as np 

In [11]:
A = np.array ([[1,2,3,4,5],
             [5,3,5,2,4]])
B = A
B [0,1] = 10 
A

array([[ 1, 10,  3,  4,  5],
       [ 5,  3,  5,  2,  4]])

In [13]:
row = [0,1,1]
col = [3,4,1]
A [row , col ]

array([4, 4, 3])

In [14]:
cond = A % 2 == 0 
A [cond]

array([10,  4,  2,  4])