In [1]:
import numpy as np 

# Lecture 2

In [2]:
A = np.array ([[1,2,3] , [4,5,6]]) 
A

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.ones ([3,3])
np.zeros ([3,3])
np.eye (5)
np.full ([3,3] , 10 )
np.arange (1,10)
np.linspace (1,5,5)

array([1., 2., 3., 4., 5.])

In [13]:
A.shape 
A.size
A.ndim
A.dtype 

dtype('int64')

In [14]:
A.astype ("str") 

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U21')

In [17]:
A.reshape ([3,2]) 
A.flatten()

array([1, 2, 3, 4, 5, 6])

# Lecture 3 

In [18]:
A [0]

array([1, 2, 3])

In [19]:
A [0, 1 ]

np.int64(2)

In [21]:
B = A 
B [0] = 1000
A

array([[1000, 1000, 1000],
       [   4,    5,    6]])

In [24]:
A = np.array ([1,2,3,4,5,6,7,8,9])
ind = [1,2,3]
A [ind]

array([2, 3, 4])

In [25]:
cond = A % 2 == 0 
A [cond]

array([2, 4, 6, 8])

# Lecture 4 

In [28]:
A = np.array ([[1,2,3] , [4,5,6] , [7,8,9] ]) 
A
A [1: , :2]

array([[4, 5],
       [7, 8]])

In [33]:
B = np.array ([[[1,2,3] , [4,5,6] ] ,
              [[6,7,8] , [9,10,11]]])
B.ndim
B
B [: ,0 , :]

array([[1, 2, 3],
       [6, 7, 8]])

# Lecture 5 

In [38]:
A = np.array ([1,2,3,4,5])
A.dtype 
A.nbytes
A = A.astype ("int32") 
A.nbytes

20

In [40]:
B = np.array (["S1" , "S2" ] , dtype = "U10")
B.dtype

dtype('<U10')

In [42]:
C = np.array ([True , False , True , False]) 
C
C.dtype 

dtype('bool')

In [46]:
D = np.array ([1 + 10j , 2 + 5j , 3 + 30j])
np.sum(A)
D.dtype 

dtype('complex128')

In [50]:
E = np.array ([[10,20] , {"2" : 2} , "Hello"] , dtype = "O")
E
E.dtype

dtype('O')

# Lecture 6

In [55]:
A = np.array ([[1,2,3] , [4,5,6]])
A = A + 10

In [59]:
A + [10,10,10]
A = np.array ([10,10,10])
B = np.array ([[1,2,3] , [4,5,6]])
B + A

array([[11, 12, 13],
       [14, 15, 16]])

# Lecture 7

In [60]:
A = np.array ([1,2,3,4,5])

In [66]:
np.mean (A)
np.std (A) 
np.var (A)
np.median (A)
np.log (A) 

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [72]:
np.min (A)
np.max (A)
np.sum (A)
np.prod (A) 
np.exp (A) 
np.linspace (1,5,5)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [85]:
np.argmin (A)
np.argmax (A)
np.cumsum (A) 
np.corrcoef (A) 
np.unique (A)
np.diff (A)
np.percentile (A , 5) 

np.float64(1.2)