In [1]:
import numpy as np 

# np.where (condition ,x, y , Array)

In [6]:
A = np.array ([10,20,30,40,50,60])
np.where (A>30 , "Yes" , "No")

array(['No', 'No', 'No', 'Yes', 'Yes', 'Yes'], dtype='<U3')

In [7]:
A = np.array ([35 ,25,100,99])
Result = np.where (A >= 35 , "PASS" ,"Fail") 
Result

array(['PASS', 'Fail', 'PASS', 'PASS'], dtype='<U4')

In [9]:
A = np.array ([-1,10,15,-4])
A = np.where (A < 0 , 0 , A) 
A

array([ 0, 10, 15,  0])

# Syntax 2 np.where (condition)

In [11]:
A = np.array ( [10,20,30,40,50] )
np.where (A > 30 )

(array([3, 4]),)

In [15]:
A = np.array ([[10,20,30] ,
             [40,50 ,20]])
B , C = np.where (A < 30 )
print ("B = " , B)
print ("C = " , C)

B =  [0 0 1]
C =  [0 1 2]


# random module

In [18]:
np.random.rand (3,3)  # 0 to 1 

array([[0.61007634, 0.27514002, 0.10635479],
       [0.07358206, 0.22316284, 0.81659141],
       [0.31834018, 0.98403161, 0.83647246]])

In [24]:
np.random.randint (1,100 , [3,3])

array([[70, 59, 66],
       [79,  6, 94],
       [35, 86, 66]], dtype=int32)

In [25]:
np.random.randn(3,3) # generate negative no 

array([[-0.12322275,  1.00165922, -0.33100334],
       [ 0.85584359, -0.43984991, -0.35754704],
       [ 1.0852563 , -0.6445195 ,  1.84021498]])

In [26]:
A = np.array ([1,2,3,4,5])
np.random.choice (A,2)

array([2, 1])

In [32]:
np.random.seed (1)
A = np.random.randint (1,100,10)
A # no change after declare 

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2], dtype=int32)

In [33]:
A = np.arange (1 ,20)