In [7]:
import numpy as np 

# Lecture 1

In [8]:
A = np.array ([1,2,3,4,5])
print (A)

[1 2 3 4 5]


In [23]:
B = np.array ([[1,2,3] , [4,5,6] ])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.ones ([3,3]) 
np.zeros ([3,3])
np.eye (5)
np.arange (1,10)
np.linspace (1,5,5) 

array([1., 2., 3., 4., 5.])

In [21]:
A.dtype 
A.ndim
A.size
A.shape 

(5,)

In [27]:
B = B.reshape ([3,2])
B = B.flatten () 
B

array([1, 2, 3, 4, 5, 6])

In [29]:
A  =  A.astype ('str')
A

array(['1', '2', '3', '4', '5'], dtype='<U21')

# Lecture 2

In [33]:
A = np.array ([1,2,3,4,5,6])
B = np.array ([[1,2,3] , [4,5,6]])

In [36]:
A[1]
B [1,1]
C = A.copy()

In [37]:
ind = [0,1,2]
A [ind]

array([1, 2, 3])

In [38]:
cond = A % 2 == 0
A [cond]

array([2, 4, 6])

# Lecture 3 

In [43]:
B
C = np.array ([[[1,2,3] ,[4,5,6] ], [[7,8,9] , [10,11,12]]])
C.ndim
C

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
B [1,1]

np.int64(5)

In [51]:
B [: ,  : ]
C [: , 1 , :]

array([[ 4,  5,  6],
       [10, 11, 12]])

# Lecture 4 

In [54]:
A = np.array ([1,2,3,4,5])
A.dtype 

dtype('int64')

In [55]:
B = np.array ([1 + 2j , 2 + 4j]) 
B.dtype

dtype('complex128')

In [57]:
C = np.array ([123 , "Str" , {"A" : 1}]) 
C.dtype

dtype('O')

In [58]:
D = np.array ([True , False , True ])
D.dtype 

dtype('bool')

In [61]:
E = np.array ([1,2,3] , dtype = "str")
E.dtype
E.nbytes

12

# Lecture 5 

In [62]:
A = np.array ([[1,2,3] , [4,5,6]])
B = np.array ([10,10,10])
C = A + B
C

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
C = A * A
C

# Lecture 6 

In [67]:
A = np.array ([1,2,3,4,5,6,7])

In [93]:
np.mean (A)
np.std (A)
np.var (A)
np.median (A) 
np.log (A) 
A = np.exp (A ) 
A.astype ("int64")

array([   2,    7,   20,   54,  148,  403, 1096])

In [83]:
np.min (A) 
np.max (A)
np.prod (A) 
np.sum (A)
np.linspace (1,11,11) 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [82]:
np.cumsum (A) 
np.argmin (A)
np.argmax (A) 
np.corrcoef (A)


np.float64(1.0)

In [84]:
np.percentile (A , 10) 

np.float64(1.6)

In [85]:
np.unique (A)

array([1, 2, 3, 4, 5, 6, 7])

In [86]:
np.diff (A)

array([1, 1, 1, 1, 1, 1])