Question 1 (10 Marks)

Create the following NumPy array:

[10, 20, 30, 40, 50]

Then:

Print the array.
Print its data type.
Print its shape.

In [2]:
import numpy as np 
A = np.array ([10,20,30,40,50])
print (A)
print (A.dtype)
print (A.shape )

[10 20 30 40 50]
int64
(5,)


Question 2 (10 Marks)

Create a NumPy array from 1 to 20.

Print:

First 5 elements
Last 5 elements
Every alternate element

In [3]:
A = np.arange (1,20)
print (A [0:5])
print (A [(len(A) - 5):])
print (A [::2])

[1 2 3 4 5]
[15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


Create a 4 × 4 array using np.arange().

Print:

Second row
Third column
Last element

In [3]:
A = np.arange (1,17)
A = A.reshape ([4,4])
print (A)
print (A [1])
print (A [: , 2])
print (A [3 , 3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[5 6 7 8]
[ 3  7 11 15]
16


Question 4 (10 Marks)

Create:

arr = np.array([12, 25, 18, 42, 30, 55, 10])

Print only the elements greater than 25 using Boolean Indexing.

In [14]:
A = np.array ([12,25,18,42,30 ,55,10])
cond = A > 25 
A [cond]

array([42, 30, 55])

Question 5 (10 Marks)

Create:

arr = np.arange(1, 11)

Print:

Sum
Mean
Maximum
Minimum
Standard Deviation

In [17]:
A = np.arange (1,11)
print ("A = ", A)
print ("Sum = " , np.sum (A))
print ("Mean = " , np.mean (A))
print ("Max = " , np.max (A))
print ("Min = " , np.min (A))
print ('Standard Deviation = ' , np.std(A))

A =  [ 1  2  3  4  5  6  7  8  9 10]
Sum =  55
Mean =  5.5
Max =  10
Min =  1
Standard Deviation =  2.8722813232690143


Question 6 (10 Marks)

Create:

arr = np.arange(1,13)

Convert it into:

3 × 4

Then reshape it into:

2 × 6

In [19]:
A = np.arange (1 , 13)
print (A)
A = A .reshape ([3,4])
print (A)
A = A.reshape ([2,6]) 
print (A)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Question 7 (10 Marks)

Generate a random integer array of 20 numbers between 10 and 100.

Print:

Maximum
Minimum
Mean

In [8]:
A = np.random.randint (10 ,100 , 20)
print (np.max(A))
print (np.min(A))
print (np.mean(A))
A

82
14
46.0


array([82, 17, 15, 34, 65, 48, 15, 80, 41, 64, 60, 14, 71, 14, 55, 77, 40,
       20, 81, 27], dtype=int32)

Question 8 (10 Marks)

Create:

arr = np.array([10,15,20,25,30,35,40])

Using np.where():

Replace every value greater than 25 with 999.

In [9]:
# wrong code 
A = np.array ([10,15,20,25,30,35,40])
cond = A > 25
A [cond] = 999 
A

# right code 
B = np.array ([10,15,20,25,30,35,40])
B = np.where (cond , 999 , A) 
B

array([ 10,  15,  20,  25, 999, 999, 999])

Question 9 (10 Marks)

Create:

arr = np.array([5,2,8,2,9,1,5,6,8])

Print:

Sorted array
Unique values

In [11]:
# wrong code 
A = np.array ([5,2,8,2,9,1,5,6,8])
print (np.unique (A))

# right Code 
A =  np.array ([5,2,8,2,9,1,5,6,8])
print (np.sort (A))
print (np.unique (A))

[1 2 5 6 8 9]
[1 2 2 5 5 6 8 8 9]
[1 2 5 6 8 9]


Question 10 (10 Marks)

Create two arrays:

A = np.array([1,2,3,4,5])

B = np.array([10,20,30,40,50])

Print:

Addition
Multiplication
Division
Square of A

In [31]:
A = np.array ([1,2,3,4,5])
B = np.array ([10,20,30,40,50])
print (A + B)
print (A * B)
print (A / B)
print (A ** 2)
      

[11 22 33 44 55]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[ 1  4  9 16 25]
