# lecture 2 

In [32]:
import numpy as np
A = np.array ([[10,20,30] ,
             [40,50,60]]) 
A

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
np.ones ([3,3])
np.zeros ([3,3]) 
np.eye (5)
np.full (10 ,10) 
np.arange (1,19) 
np.linspace (1,5,5) 

array([1., 2., 3., 4., 5.])

In [30]:
A.ndim
A.size 
A.shape
A.dtype 
A.nbytes

80

In [31]:
A.astype ("str").dtype  

dtype('<U21')

In [35]:
A.reshape ([3,2])
A.flatten ()

array([10, 20, 30, 40, 50, 60])

# Lecture 3 

In [21]:
A = np.array ([1,2,3,4,5,6,7,8,9,0 ])
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [25]:
A [0]
A [0:]
A [:10]
A [: -1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
B = A # Return view or reference 
B = A.copy () # Return valid copy 

In [27]:
ind = [4,5,6]
A [ind]

array([5, 6, 7])

In [29]:
cond = A % 2 == 0
A [cond]

array([2, 4, 6, 8, 0])

# Lecture 4

In [38]:
A = np.array ([[1,2,3,4,5,6] ,
             [4,3,2,1,5,6] ,
             [10,2,4,6,4,2] ])
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 4,  3,  2,  1,  5,  6],
       [10,  2,  4,  6,  4,  2]])

In [45]:
A.shape 
A [2,:]
A [: , 3:]
A [1 : , 1:3 ]

array([[3, 2],
       [2, 4]])

In [47]:
np.sum (A , axis = 1)

array([21, 21, 28])

In [49]:
B = np.array ([[[1,2,3,4,5] ,
               [6,7,8,9,0]] ,
              [[10,11,12,13,14],
              [15,16,17,18,19]]])
B

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9,  0]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [50]:
B [: , 1 ,:]

array([[ 6,  7,  8,  9,  0],
       [15, 16, 17, 18, 19]])

In [51]:
B [1 , : , 1:3]

array([[11, 12],
       [16, 17]])

In [52]:
B [: , 1 , 1 : 3]

array([[ 7,  8],
       [16, 17]])

# Lecture 5 

In [58]:
A = np.array (["s1","s2" , "s3",'s4'] , dtype = "U200")
A.nbytes

3200

In [62]:
A = np.array ([1 + 10j , 2 + 15j] , dtype = "complex128") 
A.dtype

dtype('complex128')

In [71]:
A = np.array ([ "Hello" , [10,12,13] , {'A' :1 }] , dtype = "O") 
A

array(['Hello', list([10, 12, 13]), {'A': 1}], dtype=object)

# Lecture 6 

In [73]:
A = np.array ( [1,2,3] )
A = A ** 2
A

array([1, 4, 9])

In [76]:
A = np.array ([1,2,3])
B = np.array ([10,10,10])
C = A + B
C

A1 = np.array ([[1,2,3] , [4,5,6]] )
A2 = np.array ([10,10,10])
print (A1 + A2)

[[11 12 13]
 [14 15 16]]


# Lecture 7

In [77]:
A = np.array ([1,2,3,4,5])

In [85]:
np.mean (A) 
np.std (A)
np.var (A)
np.median (A)
np.log (A)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [94]:
np.min (A)
np.max (A)
np.sum (A)
np.prod (A)
np.linspace (1,10,10) 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [96]:
np.exp (A)
np.diff (A)


np.int64(4)

In [102]:
np.argmin (A)
np.argmax (A)
np.cumsum (A)
np.percentile (A , 19) 
np.corrcoef (A , np.array ([15 , 13 , 12,10,8]))

array([[ 1.        , -0.99484975],
       [-0.99484975,  1.        ]])