In [1]:
import numpy as np 

In [5]:
A = [1,2,3]
B = A
B [0] = 100 
A



[100, 2, 3]

In [6]:
A = np.array ([1,2,3,4,5,6,7,8,9,10]) 
B = np.array ([11,12,13])

# Pata the 

In [30]:
np.mean (A) 
np.std (A)
np.var (A)
np.median (A)
np.log (A) 

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

#  Easy The 

In [28]:
np.min (A) 
np.max (A)
np.sum (A)
np.prod (A)
np.linspace (1,10,10) 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Hard the 

In [31]:
np.percentile (A , 10)
np.argmin (A)
np.argmax (A)
np.corrcoef (A)
np.unique (A)
np.diff (A)
np.cumsum (A)
np.exp (A)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])