In [1]:
import numpy as np 

In [2]:
A = np.array ([1,2,3,4,5]) 

In [3]:
B = np.array ([[1,2,3] ,
              [4,5,6]]) 

In [4]:
A

array([1, 2, 3, 4, 5])

In [5]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.zeros  ([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones ([2,3]) 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.arange (1, 10 , 1) 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.full ([3,3] , 9) 

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [11]:
np.linspace (1 ,3 , 5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [12]:
np.eye (3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
A.size

5

In [17]:
B.shape 

(2, 3)

In [19]:
B.ndim 

2

In [20]:
B.dtype 

dtype('int64')

In [22]:
B = B.astype ('str') 
B.dtype 

dtype('<U21')

In [24]:
B = B.reshape (3,2 ) 
B

array([['1', '2'],
       ['3', '4'],
       ['5', '6']], dtype='<U21')

In [25]:
B.flatten () 

array(['1', '2', '3', '4', '5', '6'], dtype='<U21')