In [1]:
import numpy as np 

A = np.array ([[1,2,3] ,
              [4,5,6] ,
              [7,8,9]]) 

In [2]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.sum (A , axis = 1)

array([ 6, 15, 24])

In [9]:
A [ : , 1  ]

array([2, 5, 8])

In [10]:
A [0:2 , 1:]

array([[2, 3],
       [5, 6]])

In [12]:
A [ 1: , : 2]

array([[4, 5],
       [7, 8]])

In [19]:
B = np.array([
    [[1,2,3],
     [4,5,6] ],
    [[7,8,9],
    [10,11,12]]
    ])
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
B.ndim

3

In [21]:
B [: , 1 , :]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [22]:
B [: , 0 , 0 ]

array([1, 7])