In [2]:
import numpy as np 

In [3]:
A = np.array ([1,2,3,4,5]) 

In [5]:
B = A [:3]
B

array([1, 2, 3])

In [6]:
B[0] = 100 

In [8]:
A # that return view 

array([100,   2,   3,   4,   5])

In [9]:
C = A .copy () 

In [11]:
C[1] = 1000
A
C

array([ 100, 1000,    3,    4,    5])

In [12]:
ind = [2,3,4]
A [ind]

array([3, 4, 5])

In [13]:
A [A % 2 == 0]

array([100,   2,   4])

In [36]:
L1 = np.array ([1,2,3,4,5])
L2 = L1.copy ()
print ("Before")
print ("L1 = ", L1)
print ("L2 = " , L2)
print () 

L2 [0] = 1111
print ("After")
print ("L1 = ", L1)
print ("L2 = " , L2)

Before
L1 =  [1 2 3 4 5]
L2 =  [1 2 3 4 5]

After
L1 =  [1 2 3 4 5]
L2 =  [1111    2    3    4    5]


In [38]:
ind = [2,3,4]
L1 [ind]

array([3, 4, 5])

In [40]:
cond = L1 % 2 == 0 
L1 [cond]

array([2, 4])

In [43]:
L1 = np.array ([1,2,3,4,5])
L1 = L2 
L2[0]= 1111
L1
L2

array([1111,    2,    3,    4,    5])

In [45]:
ind = [0,2,4]
L1 [ind]

array([1111,    3,    5])

In [46]:
cond = L1 % 2 == 0

In [47]:
L1[cond]

array([2, 4])