In [10]:
# install package in notebook
# !pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [11]:
import numpy as np 

In [15]:
np.zeros ([3,3]) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones ([3,5]) 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.full ([4,5] , 10 )

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [18]:
np.eye (5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.arange (1,10,2)

array([1, 3, 5, 7, 9])

In [22]:
np.linspace (0,2,5) 

array([0. , 0.5, 1. , 1.5, 2. ])

# ATTRIBUTE OF NUMPY ARRAY

In [39]:
A = np.array ([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]]) 

In [25]:
A.shape 

(4, 3)

In [26]:
A.size

12

In [29]:
A.ndim

2

In [30]:
A.dtype 

dtype('int64')

# CHANGING DATATYPE 

In [33]:
A = np.array ([1,2,3] , dtype = "float32")

A.dtype 

dtype('float32')

In [37]:
B = np.array ([1,2,3,4,5,6,7])

C = B.astype ('float64')

#B.dtype # int 64
C.dtype

dtype('float64')

# Change Shape 

In [40]:
A 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
A.reshape ([3,4]) 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Reshape Possible when possible Element pass    

In [42]:
A.reshape ([2,6]) 

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [45]:
# A.reshape ([4,6]) # Error 