# Slicing mystry 

In [5]:
import numpy as np 

A = np.array ([1,2,3,4,5])

B = A [1:5] # because it not crete copy it create view 
            # Same address of element A assine to B

print ("B = " , B)

B[0] = 1000

print ("B = " , B)
print ("A = " , A) 

B =  [2 3 4 5]
B =  [1000    3    4    5]
A =  [   1 1000    3    4    5]


# Slicing returns a view, not a copy! Changes affect the original array.**


This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

# How to create copy 

In [8]:
c = A[1:5].copy () 

c [1] = 2000

print ("c = " , c) 

print ("A = " , A)

c =  [1000 2000    4    5]
A =  [   1 1000    3    4    5]


# Fancy indexing 

In [10]:
A = np.array ([0,1,2,3,4,5,6,7,8,9,10]) 

ind = [2,4,6,8]

A[ind]

array([2, 4, 6, 8])

# CONDITION FILTER 

In [15]:
cond =  A % 2 == 0 

A [cond]

array([ 0,  2,  4,  6,  8, 10])

# Exercises for Practice

In [16]:
A = np.array ([[1,2,3],
              [4,5,6] ,
              [7,8,9]]) 

A.shape 

(3, 3)

In [19]:
A = np.array ([1.1 , 2.2 , 3.3 ])
B = A.astype ("int64") 
print( B.dtype ) 
B

int64


array([1, 2, 3])

In [20]:
A = np.array ([1,2,3,4,5,6]) 

ind = [1,3,5]

A [ind] 

array([2, 4, 6])

In [23]:
A = np.array ([1,2,3,4,5,6,7,8,9]) 

A = A.reshape ([3,3]) 

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
A = np.array ([20,60 ,100 , 40 ,80 ]) 

cond = A > 50 

A [cond]

array([ 60, 100,  80])