# Axis 

In [2]:
import numpy as np

In [48]:
A = np.array ([[1,2,3],
              [4,5,6],
              [7,8,9]]) 
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.sum (A , axis = 0) 

array([12, 15, 18])

In [50]:
np.sum (A, axis = 1 ) 

array([ 6, 15, 24])

# Access Multidimentional array 

In [51]:
A [0 , 1]

np.int64(2)

In [52]:
A [0:2 , 1:3]

array([[2, 3],
       [5, 6]])

In [53]:
A [: , 1]

array([2, 5, 8])

In [15]:
A [1:3 , 0:2 ] 

array([[4, 5],
       [7, 8]])

In [54]:
A [0]

array([1, 2, 3])

In [24]:
A [2][1]

np.int64(8)

# INDICING IN 3D ARRAY 

In [56]:
Arr = np.array ([[[1,2,3] , [4,5,6] ] ,
      [[7,8,9] , [10 ,11 ,12]]]) 

Arr.shape

(2, 2, 3)

In [57]:
Arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
Arr [1,1,1]

np.int64(11)

In [59]:
Arr [1,0,2]

np.int64(9)

In [60]:
Arr [:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [61]:
Arr [: , 0 , : ]

array([[1, 2, 3],
       [7, 8, 9]])

In [62]:
Arr[0 , : , 0 ]

array([1, 4])

In [63]:
Arr [1 , : , 1 ]

array([ 8, 11])

In [64]:
Arr [: , 0]

array([[1, 2, 3],
       [7, 8, 9]])

In [65]:
Arr [: , 0] = 0 
Arr

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])