# Vectorization 

In [2]:
import numpy as np 

In [3]:
A = np.array ([1,2,3])

A = A + 5

print (A) 

[6 7 8]


# Broadcasting 

In [5]:
A1 = np.array ([1,2,3])

A2 = np.array ([4,5,6])

A3 = A1 + A2 

A3

array([5, 7, 9])

In [9]:
print (A1) 

A1 = A1 + [10,10,10] 
# A1 = A1 + 10

A1 

[1 2 3]


array([11, 12, 13])

In [15]:
N1 = np.array ([[10,20,30] , [40,50,60]])
N2 = np.array ([1,2,3]) 

N3 = N1 + N2

print (N3)

[[11 22 33]
 [41 52 63]]
