In [1]:
import numpy as np 

In [2]:
A = np.array ([1,2,3,4,5]) 

# mean = sum of element / no of element 

In [3]:
A.mean () 

np.float64(3.0)

In [4]:
(1 + 2 + 3 + 4 + 5 ) / 5

3.0

# std = standard deviation 

In [5]:
A.std () 

np.float64(1.4142135623730951)

# var = varience 

In [7]:
A.var()

np.float64(2.0)

# min

In [8]:
A.min () 

np.int64(1)

# max 

In [10]:
A.max () 

np.int64(5)

# sum 

In [12]:
A.sum () 

np.int64(15)

# prod 

In [13]:
A.prod ()

np.int64(120)

# median 

In [16]:
np.median (A) 

np.float64(3.0)

# percentile 

In [19]:
np.percentile ( A , 50 )

np.float64(3.0)

# argmin = return min value index

In [20]:
np.argmin (A)

np.int64(0)

# argmax 

In [21]:
np .argmax (A) 

np.int64(4)

# np.corrcoef() – Compute the correlation coefficient matrix of two arrays.

In [22]:
np.corrcoef (A)

np.float64(1.0)

# np.unique() – Find the unique elements of an array.

In [24]:
np.unique (A) 

array([1, 2, 3, 4, 5])

# np.diff() – Compute the n-th differences of an array.

In [25]:
np.diff (A)

array([1, 1, 1, 1])

# np.cumsum() – Compute the cumulative sum of an array.

In [27]:
np.cumsum (A) 

array([ 1,  3,  6, 10, 15])

# np.linspace() – Create an array with evenly spaced numbers over a specified interval.

In [30]:
np.linspace (0 , 10 , 5, dtype = 'int64')

array([ 0,  2,  5,  7, 10])

# np.exp() – Compute the exponential of an array.

In [34]:
np.exp (A).astype ('int64') 

array([  2,   7,  20,  54, 148])