In [1]:
import numpy as np 

Question 1 (10 Marks)

Create a NumPy array from 5 to 50.

Print:

First 10 elements
Last 10 elements
Every 3rd element

In [68]:
A = np.arange (5,51)
print (A [:10])
print ( A[(len (A) - 10 ):] )
print (A [::3] )

[ 1  2  3  4  5  6  7  8  9 10]
[41 42 43 44 45 46 47 48 49 50]
[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


Question 2 (10 Marks)

Create a 5 × 5 array using np.arange().

Print:

First row
Last column
Center element
Last row

In [17]:
A = np.arange (1,26)
print (A)
A = A.reshape ([5,5])
print (A)
print (A [0])
print (A[: ,4])
print (A [: , 2])
print (A [-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[ 3  8 13 18 23]
[21 22 23 24 25]


Question 3 (10 Marks)

Create:

arr = np.array([45,12,67,23,89,10,54,76,32])

Using Boolean Indexing:

Print numbers greater than 40
Print numbers less than 30

In [19]:
A = np.array ([45,12,67,23,89,10,54,76,32])
print (A [A > 40])
print (A [A < 30])

[45 67 89 54 76]
[12 23 10]


Question 4 (10 Marks)

Create:

arr = np.array([2,4,6,8,10])

Print:

Square
Cube
Square Root

In [27]:
A = np.array ([2,4,6,8,10])
print (A ** 2)
print (A ** 3)
print (np.sqrt(A))

[  4  16  36  64 100]
[   8   64  216  512 1000]
[1.41421356 2.         2.44948974 2.82842712 3.16227766]


Question 5 (10 Marks)

Generate 30 random integers between 1 and 200.

Print:

Maximum`
Minimum
Mean
Standard Deviation

In [31]:
A = np.random.randint (1,200,30)
print(A.max ())
print (A.min ())
print (A.mean ())
print (A.std () )

194
4
103.83333333333333
57.62238183977549


Question 6 (10 Marks)

Create:

arr = np.arange(1,26)

Convert it into a 5 × 5 matrix.

Then print:

Second column
Fourth row
Diagonal elements

In [41]:
A = np.arange (1,26) 
A = A.reshape ([5,5])
print (A)
print (A [:,1])
print (A [3])
r = [0,1,2,3,4]
c = [0,1,2,3,4]
print (A [r,c])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 2  7 12 17 22]
[16 17 18 19 20]
[ 1  7 13 19 25]


Question 7 (10 Marks)

Create:

arr = np.array([11,22,33,44,55,66,77])

Using np.where():

Replace every value greater than 40 with 0.
Replace every value less than or equal to 40 with 1.

In [45]:
A = np.array ([11,22,33,44,55,66,77])
A = np.where (A >40 , 0 , 1)
print (A)

[1 1 1 0 0 0 0]


Question 8 (10 Marks)

Create:

arr = np.array([8,5,3,8,1,5,7,9,3,2])

Print:

Sorted array
Unique values
Reverse sorted array

In [55]:
A = np.array ([8,5,3,8,1,5,7,9,3,2])
print (np.sort (A))
print (np.unique (A))
A = np.sort (A)
print (A [::-1])

[1 2 3 3 5 5 7 8 8 9]
[1 2 3 5 7 8 9]
[9 8 8 7 5 5 3 3 2 1]


Question 9 (10 Marks)

Create two arrays:

A = np.array([2,4,6,8,10])
B = np.array([1,2,3,4,5])

Print:

Addition
Subtraction
Multiplication
Division
Modulus (%)

In [57]:
A = np.array ([2,4,6,8,10])
B = np.array ([1,2,3,4,5])
print (A + B)
print (A - B)
print (A * B)
print (A / B)
print (A % B)

[ 3  6  9 12 15]
[1 2 3 4 5]
[ 2  8 18 32 50]
[2. 2. 2. 2. 2.]
[0 0 0 0 0]


Question 10 (10 Marks)

Create a 4 × 4 random integer matrix between 10 and 50.

Print:

Shape
Data type
Maximum value
Minimum value
Mean of all elements

In [66]:
A = np.random.randint (10,50,[4,4])
print (A)
print (A.shape)
print (A.dtype )
print (np.max(A))
print (np.min (A))
print (np.mean (A))

[[39 15 46 43]
 [43 30 14 25]
 [14 23 41 17]
 [28 36 29 42]]
(4, 4)
int32
46
14
30.3125
