In [1]:
import numpy as np 

In [2]:
np.array ([1,2,3,4,5,6]) 

array([1, 2, 3, 4, 5, 6])

In [11]:
A = np.array ([[1,2,3] ,
          [4,5,6] ,
          [7,8,9]]) 

# using method 

In [5]:
np.ones ([3,3]) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.zeros ([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.eye (3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.arange (1 , 10 )

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace (0 , 1 , 3)

array([0. , 0.5, 1. ])

In [10]:
np.full ([3,3] , 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# attribute 

In [12]:
A.size 

9

In [16]:
A.ndim

2

In [17]:
A.shape 

(3, 3)

In [18]:
A.dtype 

dtype('int64')

# Change Datatype

In [21]:
A = A.astype ("int32") 

In [22]:
A.dtype 

dtype('int32')

# Reshapping array

In [27]:
A = np.array ([[1,2,3] ,
              [4,5,6]]) 

print (A.shape )

A = A.reshape ([3,2]) 

print (A)
print (A.shape ) 

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [29]:
A = A.flatten ()
A

array([1, 2, 3, 4, 5, 6])

In [32]:
A = np.array ([[1,2,3] ,
              [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
B = np.array ([1,2,3,4,5])
B

array([1, 2, 3, 4, 5])

In [33]:
np.zeros ([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones ([3,3]) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.full ([3,3] , 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [36]:
np.eye (5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.arange (1, 10 ) 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.linspace (1,5,5)

array([1., 2., 3., 4., 5.])

In [40]:
A.shape 

(2, 3)

In [42]:
A.ndim

2

In [43]:
A.size 

6

In [44]:
A.dtype 

dtype('int64')

In [46]:
A = A.astype ("float64") 
A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
A.reshape ( [ 3,2 ])

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [48]:
A.flatten () 

array([1., 2., 3., 4., 5., 6.])

In [49]:
A = np.array ([[3,4],
              [1,3] ,
              [7,8]])
A

array([[3, 4],
       [1, 3],
       [7, 8]])

In [50]:
np.ones ([3,3]) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.zeros ([3,3]) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.full ([3,3] , 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [53]:
np.eye (5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
np.arange (10 ) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.linspace (1,5,5) 

array([1., 2., 3., 4., 5.])

In [57]:
A.shape 

(3, 2)

In [60]:
A.ndim 

2

In [61]:
A.dtype 

dtype('int64')

In [62]:
A.size 

6

In [64]:
A.astype ('str')

array([['3', '4'],
       ['1', '3'],
       ['7', '8']], dtype='<U21')

In [66]:
A.reshape ([2,3] ) 

array([[3, 4, 1],
       [3, 7, 8]])

In [67]:
A.flatten () 

array([3, 4, 1, 3, 7, 8])